version: '2'
services:
  store:
    image: store
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - 'SPRING_PROFILES_ACTIVE=prod,swagger'
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_CLOUD_CONSUL_HOST=consul
      - SPRING_CLOUD_CONSUL_PORT=8500
      - 'SPRING_DATASOURCE_URL=jdbc:postgresql://store-postgresql:5432/store'
      - 'SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_OIDC_ISSUER_URI=http://keycloak:9080/auth/realms/jhipster'
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT_ID=web_app
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT_SECRET=web_app
      - JHIPSTER_SLEEP=30
    ports:
      - '8080:8080'
  store-postgresql:
    image: 'postgres:12.3'
    environment:
      - POSTGRES_USER=store
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust

  crm:
    image: crm
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - MICRONAUT_ENVIRONMENTS=prod
      - 'JDBC_URL=jdbc:postgresql://crm-postgresql:5432/crm'
      - 'MICRONAUT_SECURITY_OAUTH2_CLIENTS_OIDC_OPENID_ISSUER=http://keycloak:9080/auth/realms/jhipster'
      - MICRONAUT_SECURITY_OAUTH2_CLIENTS_OIDC_CLIENT_ID=internal
      - MICRONAUT_SECURITY_OAUTH2_CLIENTS_OIDC_CLIENT_SECRET=internal
      - JHIPSTER_SLEEP=30
  crm-postgresql:
    image: 'postgres:12.3'
    environment:
      - POSTGRES_USER=crm
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust

  consul:
    extends:
      file: consul.yml
      service: consul
  consul-config-loader:
    extends:
      file: consul.yml
      service: consul-config-loader
  keycloak:
    extends:
      file: keycloak.yml
      service: keycloak
