version: '2'
services:
  hellomhipster-app:
    image: hellomhipster
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - MICRONAUT_ENVIRONMENTS=prod
      - JDBC_URL=jdbc:mysql://hellomhipster-mysql:3306/hellomhipster?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true
      - JDBC_PASSWORD=password
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  hellomhipster-mysql:
    extends:
      file: mysql.yml
      service: hellomhipster-mysql
