version: '2'
services:
  hellomhipster-mysql:
    image: mysql:8.0.20
    # volumes:
    #     - ~/volumes/jhipster/HelloMhipster/mysql/:/var/lib/mysql/
    environment:
      - MYSQL_USER=HelloMhipster
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=hellomhipster
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 3306:3306
    command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8mb4 --explicit_defaults_for_timestamp
